env: struct_sarl

env_args:
    n_comp: 2
    discount_reward: 0.95
    k_comp : None
    state_obs: False
    state_d_rate: False
    state_alphas: False
    env_correlation: False
    campaign_cost: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 30
test_greedy: True
t_max: 1000000
