# --- COMA-IS specific parameters ---
# NOT used in our QV paper
action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 50000
mask_before_softmax: False

runner: "episode"
#batch_size_run: 6


buffer_size: 480

batch_size: 32

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "comaIS_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

mac: "is_mac"
name: "comaIS"

use_cuda: False
use_tensorboard: True
